### PR TITLE
Updating Tester address

### PR DESCRIPTION
**Pull request by jasonz6688**
### List of Changes:

- Updated the Tester address to match the new VM instance setup.
- Updated the landing page "Link Copied!" text to "Email Copied!" to match the action.
- Fix the My Account dropdown "Logout" field on the Join and Create Game pages.
- Fix the filter problem functionality with duplicates in the list.

### Notes:

- This PR fixes the issue where the Tester repository was not accessible; I think when we renewed our GCP setup, the Tester address for the VM instance got updated.

### Screencast and Images:

There are no screencasts or images attached as there are no updates to the UI.

### CODE REVIEW

**Comment by zpChris** [comment]
I'm dealing with two others issues, which I may try to fix on this PR or another.

1. The "My Account" dropdown on the Join Game page does not allow the user to Logout.
2. The filter problem functionality on the frontend lobby page fails.
  - I will likely make a screencast for this and create a new branch / PR for this fix.

**Comment by zpChris** [comment]
I fixed the first issue above, but not yet the second.

**Review by zpChris — APPROVED** [review]
I made most of the changes on this PR, but since they're all pretty obvious and were referenced by @alankbi, I'll approve and merge this in 👍

**Comment by zpChris** [comment]
I've also fixed the second problem as well - the issue was that the verified and account problems are combined but the list is not de-duplicated, so since the keys are not unique, the frontend runs into some strange problems (pun intended).

The first video below shows the original issue, and the second video shows when it is fixed.

**Problems Filter Bug**
[Problems Filter Bug](https://www.loom.com/share/c6b6cc1494774000bfe2348dfefe997c)

**Problems Filter List**
[Problems Filter List](https://www.loom.com/share/5489fd2dc63d40578dc57dd95bbdf66e)

**Review by alankbi — APPROVED** [review]
Looks good 👍

**Pull request merged**
